# Generated by Django 4.2.16 on 2024-12-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
