# Generated by Django 4.2.16 on 2024-12-18 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_ticket_capacity_remove_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationfield',
            name='created_by',
        ),
    ]
