# Generated by Django 4.2.16 on 2024-11-24 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='visitorlog',
            old_name='location',
            new_name='reason',
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='action',
            field=models.CharField(choices=[('checkin', 'Check-in'), ('checkout', 'Check-out')], max_length=10),
        ),
    ]
