# Generated by Django 4.2.16 on 2024-11-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_alter_visitorlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorlog',
            name='admin_note',
        ),
    ]
