# Generated by Django 3.2.25 on 2025-04-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_remove_visitorlog_admin_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorlog',
            name='reason',
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
