# Generated by Django 5.1.6 on 2025-04-27 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
        ('registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgetemplate',
            name='ticket',
            field=models.OneToOneField(help_text='Each ticket can have one badge template.', on_delete=django.db.models.deletion.CASCADE, related_name='badge_template', to='registration.ticket'),
        ),
        migrations.AddField(
            model_name='badgecontent',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='badges.badgetemplate'),
        ),
    ]
