# Generated by Django 4.2.16 on 2024-11-19 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badgetemplate',
            name='event',
            field=models.OneToOneField(help_text='Each event can have one badge template.', on_delete=django.db.models.deletion.CASCADE, related_name='badge_template', to='events.event'),
        ),
        migrations.AddField(
            model_name='badgecontent',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='badges.badgetemplate'),
        ),
    ]
