# Generated by Django 4.2.16 on 2024-11-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgecontent',
            name='field_name',
            field=models.CharField(choices=[('user__username', 'Username'), ('user__email', 'Email'), ('user__first_name', 'First Name'), ('user__last_name', 'Last Name'), ('user__full_name', 'Full Name'), ('ticket_type__name', 'Ticket Type'), ('event__name', 'Event Name'), ('event__location', 'Event Location'), ('registration__registered_at', 'Registration Time'), ('registration__ticket_type__price', 'Ticket Price'), ('registration__qr_code', 'QR Code')], max_length=50),
        ),
    ]
