# Generated by Django 4.2.16 on 2024-11-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_alter_badgecontent_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgecontent',
            name='field_name',
            field=models.CharField(choices=[('user__username', 'Username'), ('user__email', 'Email'), ('user__first_name', 'First Name'), ('user__last_name', 'Last Name'), ('user__full_name', 'Full Name'), ('ticket_type__name', 'Ticket Type'), ('event__name', 'Event Name'), ('event__location', 'Event Location')], max_length=50),
        ),
    ]
