# Generated by Django 3.2.25 on 2025-01-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_badgecontent_image_height_badgecontent_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgecontent',
            name='field_name',
            field=models.CharField(choices=[('user__username', 'Username'), ('user__email', 'Email'), ('user__first_name', 'First Name'), ('user__last_name', 'Last Name'), ('user__full_name', 'Full Name'), ('user__country', 'Country'), ('ticket_type__name', 'Ticket Type'), ('event__name', 'Event Name'), ('event__location', 'Event Location'), ('qr_code__qr_image', 'QR Code')], max_length=50),
        ),
    ]
