# Generated by Django 3.2.25 on 2025-01-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_registrationfield_created_by'),
        ('badges', '0007_auto_20250115_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetemplate',
            name='ticket',
            field=models.OneToOneField(help_text='Each ticket can have one badge template.', on_delete=django.db.models.deletion.CASCADE, related_name='badge_template', to='registration.ticket'),
        ),
    ]
